
name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Export
      run: |
        MOD_NAME=$(grep -oP '<TargetName>\K[^<]+' ${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj)
        echo "MOD_NAME=$MOD_NAME" >> $GITHUB_ENV
        MOD_VERSION=$(grep -oP '<Version>\K[^<]+' ${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj)
        echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV
        BUILD_DATE=$(date +'%Y-%m-%d')
        echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
      
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.MOD_NAME }} v${{ env.MOD_VERSION }} (${{ env.BUILD_DATE }})
        path: publish/${{ env.MOD_NAME }}/
        retention-days: 30
        if-no-files-found: error
